-- MySQL Script generated by MySQL Workbench
-- Mon Dec 26 17:34:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projektBP2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projektBP2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projektBP2` DEFAULT CHARACTER SET utf8 ;
USE `projektBP2` ;

-- -----------------------------------------------------
-- Table `projektBP2`.`Zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Zanr` (
  `Zanr_id` INT NOT NULL AUTO_INCREMENT,
  `Opis` TEXT NOT NULL,
  PRIMARY KEY (`Zanr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Produkcijska_kuca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Produkcijska_kuca` (
  `Produkcijska_kuca_id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(50) NOT NULL,
  `Zemlja_porijekla` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Produkcijska_kuca_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Reziser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Reziser` (
  `Reziser_id` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(20) NOT NULL,
  `Prezime` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Osvojio_nagradu` TINYINT(1) NULL DEFAULT 0,
  `Nagrada` VARCHAR(50) NULL,
  PRIMARY KEY (`Reziser_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Serija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Serija` (
  `Serija_id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(50) NOT NULL,
  `Opis` TEXT NOT NULL,
  `Ocjena_kritike` INT NULL,
  `Popularnost` INT NULL,
  `Produkcijska_kuca_Produkcijska_kuca_id` INT NULL,
  `Reziser_Reziser_id` INT NOT NULL,
  PRIMARY KEY (`Serija_id`),
  INDEX `fk_Serija_Produkcijska_kuca1_idx` (`Produkcijska_kuca_Produkcijska_kuca_id` ASC) VISIBLE,
  INDEX `fk_Serija_Reziser1_idx` (`Reziser_Reziser_id` ASC) VISIBLE,
  CONSTRAINT `fk_Serija_Produkcijska_kuca1`
    FOREIGN KEY (`Produkcijska_kuca_Produkcijska_kuca_id`)
    REFERENCES `projektBP2`.`Produkcijska_kuca` (`Produkcijska_kuca_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Serija_Reziser1`
    FOREIGN KEY (`Reziser_Reziser_id`)
    REFERENCES `projektBP2`.`Reziser` (`Reziser_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Sezona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Sezona` (
  `Sezona_id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(50) NOT NULL,
  `Opis` TEXT NOT NULL,
  `Datum_izlaska` DATE NOT NULL,
  `Broj_epizoda` INT NULL,
  `Ocjena_kritike` INT NULL,
  `Serija_Serija_id` INT NOT NULL,
  PRIMARY KEY (`Sezona_id`),
  INDEX `fk_Sezona_Serija1_idx` (`Serija_Serija_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sezona_Serija1`
    FOREIGN KEY (`Serija_Serija_id`)
    REFERENCES `projektBP2`.`Serija` (`Serija_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Epizoda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Epizoda` (
  `Epizoda_id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(50) NOT NULL,
  `Datum_izlaska` DATE NOT NULL,
  `Trajanje` TIME NOT NULL,
  `Sezona_Sezona_id` INT NOT NULL,
  PRIMARY KEY (`Epizoda_id`),
  INDEX `fk_Epizoda_Sezona_idx` (`Sezona_Sezona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Epizoda_Sezona`
    FOREIGN KEY (`Sezona_Sezona_id`)
    REFERENCES `projektBP2`.`Sezona` (`Sezona_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Film` (
  `Film_id` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(50) NOT NULL,
  `Opis` TEXT NOT NULL,
  `Trajanje` TIME NOT NULL,
  `Ocjena_kritike` INT NULL,
  `Popularnost` INT NULL,
  `Za_odrasle` TINYINT(1) NULL DEFAULT 0,
  `Dob` INT NULL,
  `Produkcijska_kuca_Produkcijska_kuca_id` INT NULL,
  `Reziser_Reziser_id` INT NOT NULL,
  PRIMARY KEY (`Film_id`),
  INDEX `fk_Film_Produkcijska_kuca1_idx` (`Produkcijska_kuca_Produkcijska_kuca_id` ASC) VISIBLE,
  INDEX `fk_Film_Reziser1_idx` (`Reziser_Reziser_id` ASC) VISIBLE,
  CONSTRAINT `fk_Film_Produkcijska_kuca1`
    FOREIGN KEY (`Produkcijska_kuca_Produkcijska_kuca_id`)
    REFERENCES `projektBP2`.`Produkcijska_kuca` (`Produkcijska_kuca_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Film_Reziser1`
    FOREIGN KEY (`Reziser_Reziser_id`)
    REFERENCES `projektBP2`.`Reziser` (`Reziser_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Glumac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Glumac` (
  `Glumac_id` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(50) NOT NULL,
  `Prezime` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Glumac_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Film_pripada_Zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Film_pripada_Zanr` (
  `Film_Film_id` INT NOT NULL,
  `Zanr_Zanr_id` INT NOT NULL,
  PRIMARY KEY (`Film_Film_id`, `Zanr_Zanr_id`),
  INDEX `fk_Film_has_Zanr_Zanr1_idx` (`Zanr_Zanr_id` ASC) VISIBLE,
  INDEX `fk_Film_has_Zanr_Film1_idx` (`Film_Film_id` ASC) VISIBLE,
  CONSTRAINT `fk_Film_has_Zanr_Film1`
    FOREIGN KEY (`Film_Film_id`)
    REFERENCES `projektBP2`.`Film` (`Film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Zanr_Zanr1`
    FOREIGN KEY (`Zanr_Zanr_id`)
    REFERENCES `projektBP2`.`Zanr` (`Zanr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Serija_pripada_Zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Serija_pripada_Zanr` (
  `Serija_Serija_id` INT NOT NULL,
  `Zanr_Zanr_id` INT NOT NULL,
  PRIMARY KEY (`Serija_Serija_id`, `Zanr_Zanr_id`),
  INDEX `fk_Serija_has_Zanr_Zanr1_idx` (`Zanr_Zanr_id` ASC) VISIBLE,
  INDEX `fk_Serija_has_Zanr_Serija1_idx` (`Serija_Serija_id` ASC) VISIBLE,
  CONSTRAINT `fk_Serija_has_Zanr_Serija1`
    FOREIGN KEY (`Serija_Serija_id`)
    REFERENCES `projektBP2`.`Serija` (`Serija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serija_has_Zanr_Zanr1`
    FOREIGN KEY (`Zanr_Zanr_id`)
    REFERENCES `projektBP2`.`Zanr` (`Zanr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Glumac_glumi_Serija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Glumac_glumi_Serija` (
  `Glumac_Glumac_id` INT NOT NULL,
  `Serija_Serija_id` INT NOT NULL,
  PRIMARY KEY (`Glumac_Glumac_id`, `Serija_Serija_id`),
  INDEX `fk_Glumac_has_Serija_Serija1_idx` (`Serija_Serija_id` ASC) VISIBLE,
  INDEX `fk_Glumac_has_Serija_Glumac1_idx` (`Glumac_Glumac_id` ASC) VISIBLE,
  CONSTRAINT `fk_Glumac_has_Serija_Glumac1`
    FOREIGN KEY (`Glumac_Glumac_id`)
    REFERENCES `projektBP2`.`Glumac` (`Glumac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glumac_has_Serija_Serija1`
    FOREIGN KEY (`Serija_Serija_id`)
    REFERENCES `projektBP2`.`Serija` (`Serija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektBP2`.`Glumac_glumi_Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektBP2`.`Glumac_glumi_Film` (
  `Glumac_Glumac_id` INT NOT NULL,
  `Film_Film_id` INT NOT NULL,
  PRIMARY KEY (`Glumac_Glumac_id`, `Film_Film_id`),
  INDEX `fk_Glumac_has_Film_Film1_idx` (`Film_Film_id` ASC) VISIBLE,
  INDEX `fk_Glumac_has_Film_Glumac1_idx` (`Glumac_Glumac_id` ASC) VISIBLE,
  CONSTRAINT `fk_Glumac_has_Film_Glumac1`
    FOREIGN KEY (`Glumac_Glumac_id`)
    REFERENCES `projektBP2`.`Glumac` (`Glumac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glumac_has_Film_Film1`
    FOREIGN KEY (`Film_Film_id`)
    REFERENCES `projektBP2`.`Film` (`Film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `projektBP2`;

DELIMITER $$
USE `projektBP2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `projektBP2`.`Reziser_BEFORE_INSERT` BEFORE INSERT ON `Reziser` FOR EACH ROW
BEGIN
	IF NEW.Nagrada != '' THEN SET NEW.Osvojio_nagradu = 1;
    ELSE SET NEW.Osvojio_nagradu = 0;
    END IF;
END$$

USE `projektBP2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `projektBP2`.`Epizoda_AFTER_INSERT` AFTER INSERT ON `Epizoda` FOR EACH ROW
BEGIN
	UPDATE Sezona SET Sezona.Broj_epizoda = Sezona.Broj_epizoda + 1 WHERE Sezona_Sezona_id = Sezona.Sezona_id;
END;$$

USE `projektBP2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `projektBP2`.`Epizoda_AFTER_DELETE` AFTER DELETE ON `Epizoda` FOR EACH ROW
BEGIN
	UPDATE Sezona SET Sezona.Broj_epizoda = Sezona.Broj_epizoda - 1 WHERE Sezona_Sezona_id = Sezona.Sezona_id;
END$$

USE `projektBP2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `projektBP2`.`Film_BEFORE_INSERT` BEFORE INSERT ON `Film` FOR EACH ROW
BEGIN
	IF NEW.Dob >= 18 THEN SET NEW.Za_odrasle = 1;
    ELSE SET NEW.Za_odrasle = 0;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
